# Copyright 2026 Jan-Willem Smaal <usenet@gispen.org>
# SPDX-License-Identifier: Apache-2.0

# General
CONFIG_MAIN_STACK_SIZE=2048

# I2S and Audio
CONFIG_I2S=y
CONFIG_AUDIO_SAMPLE_RATE=48000
CONFIG_AUDIO_BIT_WIDTH=16

# CMSIS-DSP
CONFIG_CMSIS_DSP=y
CONFIG_CMSIS_DSP_FASTMATH=y

# MIDI 1.0 Library
CONFIG_MIDI1_SERIAL=y
CONFIG_MIDI1_SERIAL_ISR_MSGQ_SIZE_MS=128
CONFIG_MIDI1_HARMONIC=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# GPIO
CONFIG_GPIO=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_I2S_LOG_LEVEL_ERR=y

# Floating Point Support for Shell/Logging
CONFIG_CBPRINTF_FP_SUPPORT=y
