import sys
import math

def harm_note_to_freq(note):
    # MIDI note 69 is A4 (440Hz)
    return 440.0 * math.pow(2.0, (note - 69) / 12.0)

def main():
    if len(sys.argv) != 3:
        print("Usage: gen_luts.py <sample_rate> <output_file>")
        sys.exit(1)

    sample_rate = float(sys.argv[1])
    output_file = sys.argv[2]

    phase_factor = 4294967296.0 / sample_rate

    phase_inc_lut = []
    for note in range(128):
        freq = harm_note_to_freq(note)
        phase_inc = int(freq * phase_factor)
        phase_inc_lut.append(phase_inc)

    velocity_lut = [0]
    for vel in range(1, 128):
        db = -30.0 + (((vel - 1) / 126.0) * 30.0)
        linear = math.pow(10.0, db / 20.0)
        q15_val = int(linear * 32767.0)
        velocity_lut.append(q15_val)

    with open(output_file, 'w') as f:
        f.write("/*\n")
        f.write(" * MACHINE-GENERATED FILE. DO NOT EDIT.\n")
        f.write(" * Generated by gen_luts.py\n")
        f.write(" */\n\n")
        f.write("#ifndef SYNTH_LUTS_GENERATED_H\n")
        f.write("#define SYNTH_LUTS_GENERATED_H\n\n")
        f.write("#include <stdint.h>\n")
        f.write("#include <arm_math.h>\n\n")
        
        f.write("static const uint32_t phase_inc_lut[128] = {\n")
        for i in range(0, 128, 8):
            chunk = phase_inc_lut[i:i+8]
            f.write("    " + ", ".join(f"{val}U" for val in chunk) + ",\n")
        f.write("};\n\n")

        f.write("static const q15_t velocity_lut[128] = {\n")
        for i in range(0, 128, 8):
            chunk = velocity_lut[i:i+8]
            f.write("    " + ", ".join(f"{val}" for val in chunk) + ",\n")
        f.write("};\n\n")

        f.write("#endif /* SYNTH_LUTS_GENERATED_H */\n")

if __name__ == "__main__":
    main()
